name: Publish statics
on:
  push:
    branches: [main]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository and checkout branch
        uses: actions/checkout@v3
      - name: Deploy to angry-hydrant.surge.sh
        uses: dswistowski/surge-sh-action@v1
        with:
          domain: "angry-hydrant.surge.sh"
          project: "."
          login: ${{ secrets.surge_login }}
          token: ${{ secrets.surge_token }}
